### ISSUE TITLE
fix: resolve import sorting conflict between isort and ruff

### ISSUE THREAD

**Issue by JimBarrows** [JimBarrows/obsidian-to-notion#13]
## Problem Description

The CI/CD pipeline is failing due to conflicting import sorting requirements between isort and ruff:
- **isort** requires a blank line between third-party imports and local imports
- **ruff** removes these blank lines

This creates an impossible situation where the code cannot satisfy both linters simultaneously.

## Current Behavior

When running isort:
```python
from behave import given, then, when
from notion_client import APIResponseError

from obsidian_to_notion.notion import DeduplicationManager, NotionMigrationClient
```

When running ruff after isort:
```python
from behave import given, then, when
from notion_client import APIResponseError
from obsidian_to_notion.notion import DeduplicationManager, NotionMigrationClient
```

## Affected Files

The following files are currently failing in CI/CD:
- `/tests/integration/steps/notion_client_steps.py`
- `/tests/integration/steps/migration_orchestrator_steps.py`
- `/tests/unit/test_main.py`
- `/tests/unit/test_notion_client.py`

## Proposed Solution

Since ruff is designed to be a drop-in replacement for multiple tools including isort, we should:

1. **Option A (Recommended)**: Configure ruff to handle import sorting and remove isort from the pipeline
   - Update `.pre-commit-config.yaml` to remove isort
   - Update `pyproject.toml` to ensure ruff's isort rules are properly configured
   - Update CI/CD workflow to only use ruff for import checking

2. **Option B**: Configure both tools to use the same import formatting rules
   - Update `pyproject.toml` to align isort and ruff configurations
   - Ensure both tools agree on the same import grouping and spacing

### For Option A (Recommended):
1. In `.pre-commit-config.yaml`, remove the isort hook
2. In `pyproject.toml`, ensure ruff has import sorting enabled:
   ```toml
   [tool.ruff]
   select = ["E", "F", "I"]  # I enables isort rules
   
   [tool.ruff.isort]
   known-first-party = ["obsidian_to_notion"]
   ```
3. Update GitHub Actions workflow to remove isort checks

### For Option B:
1. In `pyproject.toml`, configure both tools consistently:
   ```toml
   [tool.isort]
   profile = "black"
   known_first_party = ["obsidian_to_notion"]
   no_lines_before = ["LOCALFOLDER"]
   
   [tool.ruff.isort]
   known-first-party = ["obsidian_to_notion"]
   no-lines-before = ["local-folder"]
   ```

## Acceptance Criteria
- [ ] Import sorting passes in both local pre-commit hooks and CI/CD
- [ ] No conflicts between linting tools
- [ ] Clear documentation on which tool handles import sorting
- [ ] All existing test files pass import checks

## References
- [Ruff documentation on import sorting](https://docs.astral.sh/ruff/settings/#isort)
- [isort documentation](https://pycqa.github.io/isort/)
- Current CLAUDE.md mentions this issue in the Troubleshooting section
